INSERT INTO permission_groups (name)
VALUES ('DATA - Phân công công việc'),
       ('DATA - Loại hình'),
       ('DATA - Nghành nghề'),
       ('DATA - Dữ liệu khách hàng'),
       ('DATA - Nguồn khách hàng'),
       ('DATA - Phòng ban'),
       ('DATA - Lĩnh vực'),
       ('DATA - Người phụ trách'),
       ('DATA - Cấp bậc'),
       ('DATA - Chức vụ'),
       ('DATA - Quan hệ'),
       ('DATA - Phân quyền'),
       ('SALE - Dự báo nhu cầu sản phẩm'),
       ('DATA - Phân khúc');
-- Chèn dữ liệu vào bảng permissions
INSERT INTO permissions (name, code, group_id)
VALUES ('Xem Phân công công việc', 'd_allocation_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân công công việc')),
       ('Thêm Phân công công việc', 'd_allocation_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân công công việc')),
       ('Sửa Phân công công việc', 'd_allocation_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân công công việc')),
       ('Xóa Phân công công việc', 'd_allocation_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân công công việc')),
       ('Đổi trạng thái Phân công công việc', 'd_allocation_state',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân công công việc')),

       ('Xem Loại hình', 'd_business_type_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Loại hình')),
       ('Thêm Loại hình', 'd_business_type_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Loại hình')),
       ('Sửa Loại hình', 'd_business_type_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Loại hình')),
       ('Xóa Loại hình', 'd_business_type_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Loại hình')),

       ('Xem Nghành nghề', 'd_careers_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Nghành nghề')),
       ('Thêm Nghành nghề', 'd_careers_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Nghành nghề')),
       ('Sửa Nghành nghề', 'd_careers_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Nghành nghề')),
       ('Xóa Nghành nghề', 'd_careers_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Nghành nghề')),

       ('Xem Dữ liệu khách hàng', 'd_clients_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Dữ liệu khách hàng')),
       ('Thêm Dữ liệu khách hàng', 'd_clients_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Dữ liệu khách hàng')),
       ('Sửa Dữ liệu khách hàng', 'd_clients_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Dữ liệu khách hàng')),
       ('Xóa Dữ liệu khách hàng', 'd_clients_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Dữ liệu khách hàng')),
       ('Import Dữ liệu khách hàng', 'd_clients_import',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Import Dữ liệu khách hàng')),

       ('Xem Nguồn khách hàng', 'd_client_sources_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Nguồn khách hàng')),
       ('Thêm Nguồn khách hàng', 'd_client_sources_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Nguồn khách hàng')),
       ('Sửa Nguồn khách hàng', 'd_client_sources_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Nguồn khách hàng')),
       ('Xóa Nguồn khách hàng', 'd_client_sources_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Nguồn khách hàng')),

       ('Xem Phòng ban', 'd_departments_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phòng ban')),
       ('Thêm Phòng ban', 'd_departments_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phòng ban')),
       ('Sửa Phòng ban', 'd_departments_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phòng ban')),
       ('Xóa Phòng ban', 'd_departments_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phòng ban')),

       ('Xem Lĩnh vực', 'd_fields_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Lĩnh vực')),
       ('Thêm Lĩnh vực', 'd_fields_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Lĩnh vực')),
       ('Sửa Lĩnh vực', 'd_fields_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Lĩnh vực')),
       ('Xóa Lĩnh vực', 'd_fields_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Lĩnh vực')),

       ('Xem Người phụ trách', 'd_implementers_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Người phụ trách')),
       ('Thêm Người phụ trách', 'd_implementers_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Người phụ trách')),
       ('Sửa Người phụ trách', 'd_implementers_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Người phụ trách')),
       ('Xóa Người phụ trách', 'd_implementers_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Người phụ trách')),

       ('Xem Cấp bậc', 'd_levels_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Cấp bậc')),
       ('Thêm Cấp bậc', 'd_levels_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Cấp bậc')),
       ('Sửa Cấp bậc', 'd_levels_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Cấp bậc')),
       ('Xóa Cấp bậc', 'd_levels_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Cấp bậc')),

       ('Xem Chức vụ', 'd_positions_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Chức vụ')),
       ('Thêm Chức vụ', 'd_positions_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Chức vụ')),
       ('Sửa Chức vụ', 'd_positions_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Chức vụ')),
       ('Xóa Chức vụ', 'd_positions_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Chức vụ')),

       ('Xem Quan hệ', 'd_relationships_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Quan hệ')),
       ('Thêm Quan hệ', 'd_relationships_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Quan hệ')),
       ('Sửa Quan hệ', 'd_relationships_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Quan hệ')),
       ('Xóa Quan hệ', 'd_relationships_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Quan hệ')),

       ('Xem Phân quyền', 'd_role_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân quyền')),
       ('Thêm Phân quyền', 'd_role_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân quyền')),
       ('Sửa Phân quyền', 'd_role_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân quyền')),
       ('Xóa Phân quyền', 'd_role_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân quyền')),

       ('Xem Phân khúc', 'd_segments_view',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân khúc')),
       ('Thêm Phân khúc', 'd_segments_create',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân khúc')),
       ('Sửa Phân khúc', 'd_segments_update',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân khúc')),
       ('Xóa Phân khúc', 'd_segments_delete',
        (SELECT id FROM permission_groups WHERE name = 'DATA - Phân khúc')),

    ('Xem Dự báo nhu cầu sản phẩm', 's_demand_forecasts_view',
        (SELECT id FROM permission_groups WHERE name = 'SALE - Dự báo nhu cầu sản phẩm')),
       ('Thêm Dự báo nhu cầu sản phẩm', 's_demand_forecasts_create',
        (SELECT id FROM permission_groups WHERE name = 'SALE - Dự báo nhu cầu sản phẩm')),
       ('Sửa Dự báo nhu cầu sản phẩm', 's_demand_forecasts_update',
        (SELECT id FROM permission_groups WHERE name = 'SALE - Dự báo nhu cầu sản phẩm')),
       ('Xóa Dự báo nhu cầu sản phẩm', 's_demand_forecasts_delete',
        (SELECT id FROM permission_groups WHERE name = 'SALE - Dự báo nhu cầu sản phẩm'));
