INSERT INTO users.permission_groups(name, modules, sort, group_id, code)
VALUES ('Dashboard',
        ARRAY['crm', 'iss'],
        (select sort - 0.01 from users.permission_groups where code = 'project_project'),
        (select id from users.permission_groups where code = 'project'),
        'project_dashboard');
INSERT INTO users.permission_groups(name, modules, sort, group_id, code)
VALUES ('Dashboard Project',
        ARRAY['crm', 'iss'],
        0,
        (select id from users.permission_groups where code = 'project_dashboard'),
        'project_dashboard_project');
INSERT INTO users.permission_groups(name, modules, sort, group_id, code)
VALUES ('Dashboard Task',
        ARRAY['crm', 'iss'],
        1,
        (select id from users.permission_groups where code = 'project_dashboard'),
        'project_dashboard_task');

INSERT INTO users.permissions(name, code, group_id, modules, sort)
VALUES ('Trạng thái dự án', 'p_dashboard_project_state',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 0),
       ('Dự án của tôi', 'p_dashboard_my_project',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 1),
       ('Dự án quá hạn', 'p_dashboard_project_expired',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 2),
       ('Dự án sắp tới hạn', 'p_dashboard_project_near_expired',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 3),
       ('Dự án triển khai', 'p_dashboard_allocation',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 4),
       ('Số lượng Công việc - Dự án', 'p_dashboard_project_work_by_user',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 5),
       ('Top 10 dự án doanh thu dự kiến cao nhất', 'p_dashboard_project_expected_revenue',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 6),
       ('Top 10 dự án doanh thu thực tế cao nhất', 'p_dashboard_project_actual_revenue',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 7),
       ('Biểu đồ tài chính dự án', 'p_dashboard_project_financial',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 8),
       ('Chi phí dự án', 'p_dashboard_project_expense',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 9),
       ('Phụ trách chính dự án', 'p_dashboard_project_state_by_main_user',
        (select id from users.permission_groups where code = 'project_dashboard_project'),
        ARRAY['crm', 'iss'], 10),
       ('Công việc của tôi', 'p_dashboard_my_task',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 0),
       ('Công việc trong tuần', 'p_dashboard_task_in_week',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 1),
       ('Công việc quá hạn', 'p_dashboard_task_expired',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 2),
       ('Độ ưu tiên công việc', 'p_dashboard_task_priority_by_user',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 3),
       ('Giai đoạn triển khai', 'p_dashboard_task_milestone',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 4),
       ('Trạng thái công việc', 'p_dashboard_task_state_by_type',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 5),
       ('Biểu đồ tài chính dự án', 'p_dashboard_task_financial',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 6),
       ('Chi phí dự án', 'p_dashboard_task_expense',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 7),
       ('Thành viên phụ trách công việc', 'p_dashboard_task_state_by_user',
        (select id from users.permission_groups where code = 'project_dashboard_task'),
        ARRAY['crm', 'iss'], 8);
