create table if not exists users.work_calendars (
    id bigserial primary key,
    name varchar(200),
    created_at timestamp ,
    updated_at timestamp default CURRENT_TIMESTAMP,
    proposer_user_id bigint,
    enterprise_id bigint ,
    organizational_structure_id bigint,
    status varchar(50),
    type varchar(50) not null,
    is_deleted boolean default false,
    description varchar(200),
    code varchar(50),
    object_name varchar(50),
    object_id bigint ,
    start_at timestamp not null,
    end_at timestamp not null,
    goal varchar(200),
    note varchar(200),
    user_created_id bigint,
    project_ids JSONB,
    member_ids JSONB,
    client_ids JSONB,
    address JSONB
    );
