ALTER TABLE public.province
    ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE public.district
    ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE public.ward
    ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE public.country
    ADD COLUMN IF NOT EXISTS slug VARCHAR(255);